### PR TITLE
fixed Discord-Theme-Addons/macos-titlebar#1

### PR DESCRIPTION
**Pull request by boloped**

### CODE REVIEW

**Review by latorrews — APPROVED** [review]

**Comment by LuckFire** [comment]
i'm not really too sure as to why this pull request was made.. i've checked all builds and it still works on everything.

im going to close this, but if someone would like to elaborate please do so. also, next time please just make an issue request, as it's not as simple as just pushing cause i have to also update for betterdiscord as well. (unless you also compile it yourself and update for better discord)

**Comment by boloped** [comment]
Hi! I made this PR to fix an issue that appears when you dont use discord in English.
Also I committed a compiled version too,

**Comment by LuckFire** [comment]
ah okay, got it.

also, dunno how i missed that but awesome

EDIT: i was going to reopen to merge but i cant cause it's deleted..

**Comment by boloped** [comment]
Oh Bruh

**Comment by LuckFire** [comment]
if you want to resubmit you can, if not that's fine. ill try doing it when i have time to (obviously crediting.. i didnt even consider that factor when making this)

**Pull request closed without merging**
